- An abstract class is a class in which some of its methods are not defined.
- These methods can not be final, and they have the reserved word "abstract", as well as the class.
- Subclasses must overwrite such methods.
